name: Build OpenWrt 25.12

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "选择要编译的源码"
        required: true
        default: "immortalwrt/immortalwrt"
        type: choice
        options: ["immortalwrt/immortalwrt"]

      repo_branch:
        description: "选择要编译的分支"
        required: true
        default: "v25.12.1"
        type: string

      part_size:
        description: "设置rootfs大小"
        required: false
        default: 1024
        type: number

      ip_address:
        description: "设置默认IP地址"
        required: false
        default: "192.168.10.1"
        type: string

      root_password:
        description: "设置默认root密码"
        required: false
        default: "password"
        type: string

      pppoe_username:
        description: "设置默认PPPoE用户名"
        required: false
        default: ""
        type: string

      pppoe_password:
        description: "设置默认PPPoE密码"
        required: false
        default: ""
        type: string

      upload_artifact:
        description: "上传固件到Artifact"
        required: false
        default: true
        type: boolean

      upload_release:
        description: "上传固件到Releases"
        required: false
        default: true
        type: boolean

env:
  OPENWRT_DIR: openwrt
  UPLOAD_DIR: upload
  CONFIG_FILE: default.config
  TZ: Asia/Shanghai

permissions:
  contents: write
  actions: write

jobs:
  Build_OpenWrt:
    runs-on: ubuntu-latest

    env:
      OPENWRT_REPO: ${{inputs.repo_name}}
      OPENWRT_BRANCH: ${{inputs.repo_branch}}
      PART_SIZE: ${{inputs.part_size}}
      IP_ADDRESS: ${{inputs.ip_address}}
      ROOT_PASSWORD: ${{inputs.root_password}}
      PPPPOE_USERNAME: ${{inputs.pppoe_username}}
      PPPPOE_PASSWORD: ${{inputs.pppoe_password}}
      UPLOAD_ARTIFACT: ${{inputs.upload_artifact}}
      UPLOAD_RELEASE: ${{inputs.upload_release}}

    strategy:
      fail-fast: false
      matrix:
        config_name:
          - minimal
          - standard
          - full

    steps:
      - name: 克隆仓库
        uses: actions/checkout@main

      - name: 测试
        run: |
          echo "NAME_SUFFIX=${{matrix.config_name}}" >> $GITHUB_ENV
          chmod +x ./x86-64/custom_scripts/*.sh
          ./x86-64/custom_scripts/collect_upload.sh

      - name: 测试2
        run: |
          echo "GITHUB_ENV:${{env.NAME_SUFFIX}}"

  Delete_Workflow:
    needs: [Build_OpenWrt]
    runs-on: ubuntu-latest

    steps:
      - name: 删除旧的工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 2
