name: OpenWrt 25.12 Builder

on:
  workflow_dispatch:

env:
  OPENWRT_REPO: immortalwrt/immortalwrt
  OPENWRT_BRANCH: openwrt-25.12
  OPENWRT_DIR: immortalwrt
  TZ: Asia/Shanghai

jobs:
  OpenWrt_Builder:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86-64

    steps:
      - name: 克隆仓库
        uses: actions/checkout@main

      - name: 当前环境信息
        run: |
          chmod +x scripts/check.sh
          ./scripts/check.sh

      - name: 清理磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 清理磁盘空间完成
        run: |
          echo "硬盘使用情况:"
          df -hT
          echo "=============================================================================="

      - name: 初始化环境
        run: |
          chmod +x scripts/init-env.sh
          ./scripts/init-env.sh
          sudo timedatectl set-timezone ${{env.TZ}}

      - name: 克隆OpenWrt源码
        run: |
          git clone -b ${{env.OPENWRT_BRANCH}} --single-branch --depth 1 https://github.com/${{env.OPENWRT_REPO}}.git ${{env.OPENWRT_DIR}}

      - name: 复制自定义文件
        run: |
          cp -r x86-64/* ${{env.OPENWRT_DIR}}
          chmod +x ${{env.OPENWRT_DIR}}/files/etc/uci-defaults/*.sh

      - name: 配置OpenWrt Feeds
        run: |
          cd ${{env.OPENWRT_DIR}}
          chmod +x ./init-feeds.sh
          ./init-feeds.sh

      - name: 更新OpenWrt Feeds
        run: |
          cd ${{env.OPENWRT_DIR}}
          ./scripts/feeds update -a

      - name: 安装OpenWrt Feeds
        run: |
          cd ${{env.OPENWRT_DIR}}
          ./scripts/feeds install -a

      - name: 生成默认配置文件
        run: |
          cd ${{env.OPENWRT_DIR}}
          cp default.config .config 
          make defconfig

      - name: 下载依赖包
        id: download
        run: |
          cd ${{env.OPENWRT_DIR}}
          make download -j $(($(nproc)+1)) V=s || make download -j1 V=s

      - name: 编译固件
        id: compile
        run: |
          cd ${{env.OPENWRT_DIR}}
          echo "KERNEL_VERSION=$(grep -oP 'LINUX_VERSION:=\K.*' include/kernel.mk)" >> $GITHUB_ENV
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j $(($(nproc)+1)) V=s || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "COMPILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV
          echo "COMPILE_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: 编译后磁盘使用情况
        run: |
          echo "硬盘使用情况:"
          df -hT
          echo "=============================================================================="

      - name: 组织编译后的固件
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd ${{env.OPENWRT_DIR}}
          mkdir -p upload

          cp -rf .config upload/
          mv bin/targets/x86/64/immortalwrt-x86-64-generic-rootfs.tar.gz upload/immortalwrt-x86-64-generic-rootfs-${{env.COMPILE_TIME}}.tar.gz
          mv bin/targets/x86/64/immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz upload/immortalwrt-x86-64-generic-squashfs-combined-efi-${{env.COMPILE_TIME}}.img.gz

      - name: 上传固件到Artifacts
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@main
        with:
          name: ${{env.OPENWRT_BRANCH}}-${{env.COMPILE_DATE}}
          path: upload

      - name: 上传固件到Releases
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: ncipollo/release-action@main
        with:
          name: ${{env.OPENWRT_BRANCH}}-${{env.COMPILE_DATE}}
          allowUpdates: true
          removeArtifacts: true
          tag: ${{env.OPENWRT_BRANCH}}-${{env.COMPILE_DATE}}
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: upload/*
          body: |
            **This is ${{env.OPENWRT_BRANCH}} firmware for x86-64**
            ### 📒 固件信息
            - 💻 平台架构: x86-64
            - ⚽ 固件源码: https://github.com/${{env.OPENWRT_REPO}}
            - 💝 源码分支: ${{env.OPENWRT_BRANCH}}
            - 🚀 内核版本: ${{env.KERNEL_VERSION}}
            - 🌐 默认地址: 192.168.10.1
            - 🔑 默认密码: password
            ### 🧊 固件版本
            - 固件编译前最后一次→[主源码](https://github.com/${{env.OPENWRT_REPO}})更新记录
            - ${{env.COMPILE_DATE}}

  Delete_Workflow:
    needs: [OpenWrt_Builder]
    runs-on: ubuntu-latest
    steps:
      - name: 删除旧的工作流运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 2
